--- #YAML:1.0
name:               Mail-DWIM
version:            0.06
abstract:           Do-What-I-Mean Mailer
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:     0
    Log::Log4perl:  1
    Mail::Mailer:   0
    Sys::Hostname:  1
    Test::More:     0
    YAML:           0
resources:
    repository:  http://github.com/mschilli/mail-dwim-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
